let express=require("express")
const {add, login, fpwd, vpwd, respwd, gettask} = require("../controllers/controller")
const { addtask, emphome, updst, disp, del, reas } = require("../controllers/taskcon")
let rt=express.Router()
rt.post("/reg",add)
rt.post("/login",login)
rt.get("/fpwd/:id",fpwd)
rt.post("/fpwd",vpwd)
rt.post("/respwd",respwd)
rt.post("/addtask",addtask)
rt.get("/gettask/:dept",gettask)
rt.get("/home/:eid",emphome)
rt.get("/updst/:tid/:st",updst)
rt.get("/disp",disp)
rt.delete("/del/:tid",del)
rt.post("/reas/:tid",reas)
module.exports=rt